### PR TITLE
Avoid buggy palette-color TIFF images

### LINKED ISSUE #1975: FolderImageCache stores broken TIFF favicons
FolderImageCache uses NSImage's `TIFFRepresentation` to create data objects of website favicons that are then stored on disk. The resulting TIFF sometimes break the images, those images look cropped and have vertical stripes. When a favicon is first loaded from an ICO file it displays normally, but will have those issues after Vienna restarts and loads the TIFF from its cache.

NSImage from favicon.ico
Image

NSImage from xkcd_com.tiff
Image

| ICO | TIFF |
|:---:|:---:|
|  Image | Image  |
| Image  | Image  |

It's not clear why this happens and when this issue has started to appear. The TIFF look like this in Finder and Preview too.

One solution might be to avoid TIFF and simply store the original ICO files or use an archival format like NSKeyedArchiver.

### PR DESCRIPTION
**Pull request by Eitot**
Resolves #1975 

macOS 15 and 26 beta do not support palette-color TIFF images correctly. These images shall now be converted by applying the sRGB color space.

### CODE REVIEW

**Comment by Eitot** [comment]
This doesn't fix images that are already stored on disk. Vienna has no function to clear out cached icons or reload them. We could add migration code to clear out all icons once, or we could provide menu actions to reload all or individual icons, like "force refreshing" a feed.

**Comment by barijaona** [comment]
> Vienna has no function to clear out cached icons or reload them.

Vienna has a menu command "File -> Refresh Folder Images" that reloads the images.
It does not purge images from deleted feeds, though.

**Comment by Eitot** [comment]
> > Vienna has no function to clear out cached icons or reload them.
> 
> Vienna has a menu command "File -> Refresh Folder Images" that reloads the images. It does not purge images from deleted feeds, though.

I added a commit to change this behaviour.

**Comment by Eitot** [comment]
@josh64x2 Can you test this on macOS 14?

**Comment by Eitot** [comment]
One interesting thing I discovered: macresearch.org redirects `/favicon.ico` to an SVG icon which can be initialised as an NSImage (at least on macOS 15). It uses a private _NSSVGImageRep class. NSImage `TIFFRepresentation` works with this too. One downside is that the generated TIFF image is enormous: on my Mac it is 14,7 MB large.

File: Vienna/Sources/Models/FolderImageCache.m [hunk 1]
```diff
@@ -36,110 +36,127 @@ + (FolderImageCache *)defaultCache
...
-        imagesCacheFolder = imagesURL.path;
-        if (![fileManager fileExistsAtPath:imagesCacheFolder isDirectory:&isDir]) {
-            if (![fileManager createDirectoryAtPath:imagesCacheFolder withIntermediateDirectories:YES attributes:nil error:nil]) {
-                NSLog(@"Cannot create image cache at %@. Will not cache folder images in this session.", imagesCacheFolder);
-                imagesCacheFolder = nil;
-            }
-            initializedFolderImagesArray = YES;
-            return;
+    // macOS 15 does not handle images with indexed pixel samples correctly.
+    // Those images have to be converted.
```
Comment (barijaona) [inline Vienna/Sources/Models/FolderImageCache.m:121]: The comment would be clearer if it explicitly stated that we always store in RGB color space

**Comment by barijaona** [comment]
> > > Vienna has no function to clear out cached icons or reload them.
> > 
> > 
> > Vienna has a menu command "File -> Refresh Folder Images" that reloads the images. It does not purge images from deleted feeds, though.
> 
> I added a commit to change this behaviour.

I don't see a change regarding this. Images from feeds which have been deleted from database remain in the cache folder.
(it's just a remark, fixing this now is not required)

**Review by barijaona — CHANGES_REQUESTED** [review]
A comment could be improved.
The issue of orphaned images remains.

**Comment by barijaona** [comment]
> @josh64x2 Can you test this on macOS 14?

I have tested on macOS 10.13.6 (High Sierra ) and it works correctly.

**Comment by Eitot** [comment]
> > > > Vienna has no function to clear out cached icons or reload them.
> > > 
> > > 
> > > Vienna has a menu command "File -> Refresh Folder Images" that reloads the images. It does not purge images from deleted feeds, though.
> > 
> > 
> > I added a commit to change this behaviour.
> 
> I don't see a change regarding this. Images from feeds which have been deleted from database remain in the cache folder. (it's just a remark, fixing this now is not required)

Sorry, I misread your comment. I thought you meant purging cached images in general. I am not planning to change that in this PR, as there are more things consider.

**Review by barijaona — APPROVED** [review]

**Comment by josh64x2** [comment]
I did verify everything appears to work as expected on macOS 14.
